package se.umu.cs.joni0436.thirty.model
// ONE WHEN USER IS THROWING DICES
// 2ND IS WHEN 1 ROUND IS OVER AND USER PICKS SCORE
// 3RD IS WHEN ALL 10 ROUNDS HAS BEEN DONE
enum class GameState(s:String) {
    ROLLING_STATE("ROLL_THE_DICE"),
    PICKING_SCORE_STATE("PICK_SCORE"),
    GAME_COMPLETE_STATE("GAME_COMPLETE"),
    GAME_START("GAME_STARTING")
}