package se.umu.cs.joni0436.thirty.model
// ONE WHEN USER IS THROWING DICES
// 2ND IS WHEN 1 ROUND IS OVER AND USER PICKS SCORE
// 3RD IS WHEN ALL 10 ROUNDS HAS BEEN DONE
enum class GameState(s:String) {
    ROLLING_STATE("AMOUNT_OF_ROLLS"),
    PICKING_SCORE_STATE("AMOUNT_OF_ROUNDS"),
    GAME_COMPLETE_STATE("GAME_COMPLETE")
}